### ISSUE TITLE
An attack-workbench compatible capec 3.5 stix dataset

### ISSUE THREAD

**Issue by highkay** [mitre-attack/attack-stix-data#10]
[stix-capec.json.converted.json.zip](https://github.com/mitre-attack/attack-stix-data/files/7285273/stix-capec.json.converted.json.zip)

- combine/format the text into description
- translate x_mitre_xxxx properties
- map parent-child technology as sub-technology
- organize the data for attack-workbench compatible(including relationship generating)

If the work could be helpful, I would opensource the convent tool later and make a more official pr.

**Comment by isaisabel** [comment]
Hi @highkay,

Thanks for reaching out! We're not actually taking contributions to the official ATT&CK dataset via this means. If you want to contribute to the official ATT&CK knowledge base, please see our [contribute](https://attack.mitre.org/resources/contribute/) page for instructions. 

If you've created your own Workbench collection and want to share it with others, we encourage you to put it on a repo of your own -- optionally with a collection index for ease of distribution. [We have tools available on this repository](https://github.com/mitre-attack/attack-stix-data/tree/master/util) (which will soon be included in [mitreattack-python](https://github.com/mitre-attack/mitreattack-python)) to help the community set up their own public-facing datasets. 

The ATT&CK Workbench is designed specifically to facilitate this decentralized data system where different data providers independently maintain interconnected and related datasets to data consumers. So it is preferable to host (and maintain) your own data instead of contributing it to a centralized repository of datasets like this one.
