### ISSUE TITLE
Relationships microlibrary Filter argument

### ISSUE THREAD

**Issue by Abadacor** [mitre-attack/attack-stix-data#12]
Hello,

In the function _get_related(...)_ from the relationships microlibrary code snippet in file _USAGE.md_ the fourth filter creates a situation where variable _relationships_ is always empty.

I haven't tested every possibility but I get this result with functions:
* _software_used_by_groups(thesrc)_
* _groups_using_software(thesrc)_
* _techniques_used_by_groups(thesrc)_
* _groups_using_technique(thesrc)_
* _mitigation_mitigates_techniques(thesrc)_
* _technique_mitigated_by_mitigations(thesrc)_

It appears that by only filtering out the revoked objects everything works just fine.
I use the local data from file _enterprise-attack.json_ for my work.

If someone could double check that'd be awesome.

PS: In the case I'm wrong there still is a mismatched quote with a double quote in that same line.

**Comment by jondricek** [comment]
@Abadacor - I know this issue is closed with the recent PR above, but I realized I never thanked you for pointing out the issue in the first place. Sorry about that! You were totally right about both the mismatched quote (fixed!) and the improper filtering. The filtering issue is actually resolved later in the `USAGE` document, but I implemented it in the section you mentioned and addressed it there.

If this works for you, great! And if you have any other suggestions, go ahead and let us know. Thanks again!
