### ISSUE TITLE
Use TAGs for the corresponding version of MITRE ATT&CK

### ISSUE THREAD

**Issue by MaurizioCasciano** [mitre-attack/attack-stix-data#45]
Provide tags when releasing a new version of MITRE ATT&CK data
as done for the https://github.com/mitre/cti repository.

**Comment by ElJocko** [comment]
We've previously used the Collection Index file to indicate when changes to the data have been made, since this works automatically with ATT&CK Workbench. We will continue to use the Collection Index as the main indicator of changes. 

However, recognizing that some users may be retrieving the STIX 2.1 data from this repository without using Workbench, we will start adding a tag and publishing a release for each new version. We've started by adding these this for v14.1.
